version: '3.7'
services:

  # webpack hmr works in Docker with this:
  # https://github.com/AirWick219/react-rails-hmr-docker-example


  # debug with image: yeasy/simple-web:latest

  # https://codewithhugo.com/docker-compose-local-https/

  ## RUNNING...

  # to use the dev env locally, use:
  # docker-compose -f docker-compose.development.yml up
  # building a fresh copy just needs `--build` added at the end

  ## TESTS...

  # while it's up and running locally, use these to run tests:
  # docker-compose run -e "RAILS_ENV=test" taco_web rake db:create db:migrate
  # docker-compose run -e "RAILS_ENV=test" taco_web rake test

  taco_db:
    image: postgres:9.6
    volumes:
      - pg-data:/var/lib/postgresql/data
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_MULTIPLE_DATABASES=taco_dev,taco_test,taco_prod
    restart: on-failure
    deploy:
      update_config:
        parallelism: 1
        order: start-first
        failure_action: rollback
        delay: 10s
      restart_policy:
        condition: failure
        delay: 5s
        max_attempts: 3
        window: 120s
        #   resources:
        #     limits:
        #       cpus: '0.30'
        #       memory: 256M
        #     reservations:
        #       cpus: '0.15'
        #       memory: 256M

  taco_web:
    build:
      context: .
      dockerfile: web.Dockerfile
    image: jterhorst/taco-rails
    # image: yeasy/simple-web:latest
    command: "./startup_test.sh"
    volumes:
      - web-project:/web
    # Required for debug breakpoints
    tty: true
    stdin_open: true
    ipc: host
    environment:
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - NODE_ENV=test
      - RAILS_ENV=test
      - MASTER_KEY
      - RAILS_MASTER_KEY
    #   - RAILS_SERVE_STATIC_FILES=true
    ports: 
      - "8080:8080"
      - "3035:3035"
    depends_on:
      - taco_db
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  taco_worker:
    build:
      context: .
      dockerfile: web.Dockerfile
    image: jterhorst/taco-rails
    command: "bundle exec bin/rake jobs:work"
    volumes:
      - web-project:/web
    environment:
      - NODE_ENV=test
      - RAILS_ENV=test
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - MASTER_KEY
      - RAILS_MASTER_KEY
    depends_on:
      - taco_db
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 5
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

volumes:
  pg-data:
  web-project:
    driver: local
    driver_opts:
      type: none
      device: $PWD
      o: bind
