version: '3.3'
services:

  # https://codewithhugo.com/docker-compose-local-https/

  # to use the dev env locally, use:
  # docker-compose -f docker-compose.development.yml up

  taco_db:
    image: postgres:9.6
    volumes:
      - pg-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB=taco_dev
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  taco_web: &taco_app
    build:
      context: .
      dockerfile: web.Dockerfile
    image: jterhorst/taco-rails
    volumes:
      - ./:/web
    environment:
      - VIRTUAL_HOST=taco.docker
      - VIRTUAL_PORT=8080
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - NODE_ENV=development
      - RAILS_ENV=development
      - RAILS_SERVE_STATIC_FILES=true
      - MASTER_KEY
      - RAILS_MASTER_KEY
    ports: 
      - 8080
    depends_on:
      - taco_db
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 1
      restart_policy:
        condition: on-failure

  taco_worker:
    <<: *taco_app
    command: "bundle exec bin/rake jobs:work"
    environment:
      - NODE_ENV=development
      - RAILS_ENV=development
      - POSTGRES_HOST
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - MASTER_KEY
      - RAILS_MASTER_KEY
    depends_on:
      - taco_db
    restart: on-failure
    deploy:
      mode: replicated
      replicas: 5
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]

  proxy:
    image: jwilder/nginx-proxy:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx/certs:/etc/nginx/certs
    depends_on:
      - taco_web
    restart: unless-stopped

volumes:
  pg-data: