name: Rails tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Run Rake test suite via Docker container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build stack
      run: |
        echo "${{ secrets.MASTER_KEY }}" > config/master.key
        echo "${{ secrets.ENV }}" > .env
        docker-compose -f docker-compose.development.yml up -d --build
    - name: Run tests
      run: |
        docker-compose run -e "RAILS_ENV=test NODE_ENV=test" taco_web npm install
        docker-compose run -e "RAILS_ENV=test NODE_ENV=test" taco_web bundle exec rails webpacker:compile
        docker-compose run -e "RAILS_ENV=test NODE_ENV=test" taco_web rake db:create db:migrate
        docker-compose run -e "RAILS_ENV=test NODE_ENV=test" taco_web rake test
