name: Rails tests

on: pull_request

jobs:
  build:
    name: Run Rake test suite via Docker container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build stack
      run: |
        echo "${{ secrets.MASTER_KEY }}" > config/master.key
        echo "${{ secrets.ENV }}" > .env
        docker login --username jterhorst --password ${{ secrets.DOCKER_HUB_TOKEN }}
        docker build -f web.Dockerfile -t jterhorst/taco-rails:$GITHUB_RUN_ID -t jterhorst/taco-rails:latest .
    - name: Run tests
      run: |
        docker-compose -f docker-compose.test.yml up -d
        CYPRESS_BASE_URL=http://localhost:8080 ./deployment/wait-until-web-ready.sh
        echo "container booted. starting tests..."
        docker-compose run -e "RAILS_ENV=test" -e "NODE_ENV=test" taco_web npm install
        docker-compose run -e "RAILS_ENV=test" -e "NODE_ENV=test" taco_web bundle exec rails webpacker:compile
        docker-compose run -e "RAILS_ENV=test" -e "NODE_ENV=test" taco_web rake db:create db:migrate
        docker-compose run -e "RAILS_ENV=test" -e "NODE_ENV=test" taco_web rake test
        ./node_modules/.bin/cypress install
        CYPRESS_BASE_URL=http://localhost:8080 ./node_modules/.bin/cypress run --record --key 84ef6f9b-9832-4435-9739-ba53339c61ce
    - name: Spit out logs on failure
      if: ${{ failure() }}
      run: |
        docker-compose logs
    - name: Upload Cypress recordings
      if: ${{ always() }}
      uses: actions/upload-artifact@v2
      with:
        name: cypress-videos
        path: cypress/videos/
