name: Rails tests

on: pull_request

jobs:
  build:
    name: Run Rake test suite via Docker container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build stack
      run: |
        echo "${{ secrets.MASTER_KEY }}" > config/master.key
        echo "${{ secrets.ENV }}" > .env
        docker login --username jterhorst --password ${{ secrets.DOCKER_HUB_TOKEN }}
        docker build -f web.Dockerfile -t jterhorst/taco-rails:$GITHUB_RUN_ID -t jterhorst/taco-rails:latest .
    - name: Run tests
      run: |
        sudo apt install libnss3-tools
        test -d ~/.linuxbrew && eval $(~/.linuxbrew/bin/brew shellenv)
        test -d /home/linuxbrew/.linuxbrew && eval $(/home/linuxbrew/.linuxbrew/bin/brew shellenv)
        test -r ~/.bash_profile && echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.bash_profile
        echo "eval \$($(brew --prefix)/bin/brew shellenv)" >>~/.profile
        brew install mkcert
        mkcert -install
        mkcert taco.docker localhost 127.0.0.1
        cp ./taco.docker+2.pem ./nginx/certs/taco.docker.crt
        cp ./taco.docker+2-key.pem ./nginx/certs/taco.docker.key
        echo "127.0.0.1 taco.docker" | sudo tee -a /etc/hosts
        docker-compose -f docker-compose.development.yml up -d
        docker-compose run -e "RAILS_ENV=test" -e "NODE_ENV=test" taco_web npm install
        docker-compose run -e "RAILS_ENV=test" -e "NODE_ENV=test" taco_web bundle exec rails webpacker:compile
        docker-compose run -e "RAILS_ENV=test" -e "NODE_ENV=test" taco_web rake db:create db:migrate
        docker-compose run -e "RAILS_ENV=test" -e "NODE_ENV=test" taco_web rake test
        ./node_modules/.bin/cypress install
        ./node_modules/.bin/cypress run

