name: Deploy latest built image

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Run Rake test suite via Docker container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build stack
      run: |
        echo "${{ secrets.MASTER_KEY }}" > config/master.key
        echo "${{ secrets.ENV }}" > .env
        docker login --username jterhorst --password ${{ secrets.DOCKER_HUB_TOKEN }}
        docker build -f web.Dockerfile -t jterhorst/taco-rails:$GITHUB_RUN_ID -t jterhorst/taco-rails:latest .
    - name: Push to docker
      run: |
        docker push jterhorst/taco-rails:latest
    - name: Deploy
      run: |
        mkdir ~/.ssh
        echo "" > ~/.ssh/known_hosts
        echo "${{ secrets.DOCKER_SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        echo "${{ secrets.DOCKER_SSH_PUBLIC_KEY }}" > ~/.ssh/id_rsa.pub
        chmod 400 ~/.ssh/id_rsa
        chmod 400 ~/.ssh/id_rsa.pub
        ssh-keyscan -H supertaco.dev > ~/.ssh/known_hosts
        ssh-keyscan -H 142.93.178.223 >> ~/.ssh/known_hosts
        ssh root@supertaco.dev "cd taco-rails-docker && git fetch origin && git reset --hard origin/master && ./deployment/deploy.sh"
    