name: Deploy latest built image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Run Rake test suite via Docker container
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v2
    - name: Uses Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
  	    node-version: ${{ matrix.node-version }}
    - run: npm install -g yarn
    - name: Deploy
      run: |
        unzip -P ${{ secrets.MACHINES_ZIP_PASSWORD }} machines.zip
        npm install -g machine-share
        machine-import taco-4-15-node-1.zip
        docker-machine ssh taco-4-15-node-1 "cd taco-rails-docker; git fetch origin; git reset --hard origin/master; ./deployment/deploy.sh;"
