name: Deploy latest built image

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# docker-machine ssh taco-4-15-node-1 "cd taco-rails-docker; git fetch origin; git reset --hard origin/master; ./deployment/deploy.sh;"

jobs:
  build:
    name: Run Rake test suite via Docker container
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v1
      with:
        node-version: '12'
    - name: Deploy
      run: |
        unzip -P ${{ secrets.MACHINES_ZIP_PASSWORD }} machines.zip
        unzip taco-4-15-node-1.zip
        cp id_rsa ~/.ssh/taco_id_rsa
        cp id_rsa.pub ~/.ssh/taco_id_rsa.pub
        ./rdocker.sh root@142.93.178.223 "cd taco-rails-docker; git fetch origin; git reset --hard origin/master; ./deployment/deploy.sh;"
        
